# Generated by Django 5.2.11 on 2026-02-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "PURCHASE"),
                    ("CONSUMPTION", "CONSUMPTION"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("PRODUCTION", "PRODUCTION"),
                ],
                max_length=16,
            ),
        ),
    ]
