# Generated by Django 5.2.11 on 2026-02-24 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(
                        default="default", editable=False, max_length=32, unique=True
                    ),
                ),
                ("active_template", models.CharField(default="classic", max_length=64)),
                ("available_templates", models.JSONField(blank=True, default=list)),
                ("site_name", models.CharField(default="Mr Quentinha", max_length=120)),
                (
                    "site_title",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("meta_description", models.TextField(blank=True, default="")),
                ("primary_color", models.CharField(default="#FF6A00", max_length=32)),
                ("secondary_color", models.CharField(default="#1F2937", max_length=32)),
                ("dark_bg_color", models.CharField(default="#0F172A", max_length=32)),
                ("android_download_url", models.URLField(blank=True, default="")),
                ("ios_download_url", models.URLField(blank=True, default="")),
                ("qr_target_url", models.URLField(blank=True, default="")),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portal config",
                "verbose_name_plural": "Portal config",
            },
        ),
        migrations.CreateModel(
            name="PortalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(db_index=True, max_length=64)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("cardapio", "Cardapio"),
                            ("sobre", "Sobre"),
                            ("como-funciona", "Como funciona"),
                            ("contato", "Contato"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("title", models.CharField(blank=True, default="", max_length=180)),
                ("body_json", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="portal.portalconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "template_id", "page", "key"),
                        name="portal_section_unique_per_template_page",
                    )
                ],
            },
        ),
    ]
