# Generated by Django 5.2.11 on 2026-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalconfig",
            name="client_active_template",
            field=models.CharField(default="client-classic", max_length=64),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="client_available_templates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
