# Generated by Django 5.2.11 on 2026-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_portalconfig_client_active_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalconfig",
            name="admin_base_url",
            field=models.URLField(default="http://mrquentinha:3002"),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="admin_domain",
            field=models.CharField(default="admin.mrquentinha.local", max_length=180),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="api_domain",
            field=models.CharField(default="api.mrquentinha.local", max_length=180),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="backend_base_url",
            field=models.URLField(default="http://mrquentinha:8000"),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="client_base_url",
            field=models.URLField(default="http://mrquentinha:3001"),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="client_domain",
            field=models.CharField(default="app.mrquentinha.local", max_length=180),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="cors_allowed_origins",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="local_hostname",
            field=models.CharField(default="mrquentinha", max_length=120),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="local_network_ip",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="portal_base_url",
            field=models.URLField(default="http://mrquentinha:3000"),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="portal_domain",
            field=models.CharField(default="www.mrquentinha.local", max_length=180),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="proxy_base_url",
            field=models.URLField(default="http://mrquentinha:8088"),
        ),
        migrations.AddField(
            model_name="portalconfig",
            name="root_domain",
            field=models.CharField(default="mrquentinha.local", max_length=180),
        ),
    ]
