# Generated by Django 5.2.11 on 2026-02-26 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_portalconfig_admin_base_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portalconfig",
            name="api_base_url",
            field=models.URLField(default="https://10.211.55.21:8000"),
        ),
        migrations.CreateModel(
            name="MobileRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_version", models.CharField(max_length=64)),
                ("build_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Na fila"),
                            ("BUILDING", "Compilando"),
                            ("TESTING", "Testando"),
                            ("SIGNED", "Assinado"),
                            ("PUBLISHED", "Publicado"),
                            ("FAILED", "Falhou"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "update_policy",
                    models.CharField(
                        choices=[("OPTIONAL", "Opcional"), ("FORCE", "Obrigatoria")],
                        default="OPTIONAL",
                        max_length=16,
                    ),
                ),
                ("is_critical_update", models.BooleanField(default=False)),
                (
                    "min_supported_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "recommended_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("api_base_url_snapshot", models.URLField(blank=True, default="")),
                (
                    "host_publico_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "android_relative_path",
                    models.CharField(
                        default="app/downloads/android.apk", max_length=255
                    ),
                ),
                (
                    "ios_relative_path",
                    models.CharField(default="app/downloads/ios", max_length=255),
                ),
                ("android_download_url", models.URLField(blank=True, default="")),
                ("ios_download_url", models.URLField(blank=True, default="")),
                (
                    "android_checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "ios_checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("release_notes", models.TextField(blank=True, default="")),
                ("build_log", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_releases",
                        to="portal.portalconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_releases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("config", "release_version", "build_number"),
                        name="mobile_release_unique_version_build",
                    )
                ],
            },
        ),
    ]
