# Generated by Django 5.2.11 on 2026-02-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_portalconfig_api_base_url_mobilerelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalconfig",
            name="auth_providers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
