# Generated by Django 5.2.11 on 2026-02-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_portalconfig_auth_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalconfig",
            name="payment_providers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
