# Generated by Django 5.2.11 on 2026-03-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_portalconfig_installer_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalsection",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("cardapio", "Cardapio"),
                    ("sobre", "Sobre"),
                    ("como-funciona", "Como funciona"),
                    ("suporte", "Suporte"),
                    ("wiki", "Wiki"),
                    ("contato", "Contato"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
