# Generated by Django 5.2.11 on 2026-03-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_alter_portalsection_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalsection",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("cardapio", "Cardapio"),
                    ("app", "App"),
                    ("sobre", "Sobre"),
                    ("como-funciona", "Como funciona"),
                    ("suporte", "Suporte"),
                    ("wiki", "Wiki"),
                    ("contato", "Contato"),
                    ("pedidos", "Pedidos"),
                    ("conta", "Conta"),
                    ("privacidade", "Privacidade"),
                    ("termos", "Termos"),
                    ("lgpd", "LGPD"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
