# Generated by Django 5.2.11 on 2026-02-23 23:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "REVENUE"),
                            ("EXPENSE", "EXPENSE"),
                            ("ASSET", "ASSET"),
                            ("LIABILITY", "LIABILITY"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "IN"), ("OUT", "OUT")], max_length=8
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_movements",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-movement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="APBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_name", models.CharField(max_length=180)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("PAID", "PAID"),
                            ("CANCELED", "CANCELED"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_bills",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("reference_type__isnull", False),
                            models.Q(("reference_type", ""), _negated=True),
                            ("reference_id__isnull", False),
                        ),
                        fields=("reference_type", "reference_id"),
                        name="finance_apbill_reference_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ARReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("RECEIVED", "RECEIVED"),
                            ("CANCELED", "CANCELED"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_receivables",
                        to="finance.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_receivables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("reference_type__isnull", False),
                            models.Q(("reference_type", ""), _negated=True),
                            ("reference_id__isnull", False),
                        ),
                        fields=("reference_type", "reference_id"),
                        name="finance_arreceivable_reference_unique",
                    )
                ],
            },
        ),
    ]
