# Generated by Django 5.2.11 on 2026-02-24 01:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("AP_PAID", "AP_PAID"),
                            ("AR_RECEIVED", "AR_RECEIVED"),
                            ("CASH_IN", "CASH_IN"),
                            ("CASH_OUT", "CASH_OUT"),
                            ("ADJUSTMENT", "ADJUSTMENT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("reference_type", models.CharField(max_length=32)),
                ("reference_id", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_credits",
                        to="finance.account",
                    ),
                ),
                (
                    "debit_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_debits",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reference_type", "reference_id", "entry_type"),
                        name="finance_ledger_reference_entry_type_unique",
                    )
                ],
            },
        ),
    ]
