# Generated by Django 5.2.11 on 2026-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="procurement/receipts/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="label_back_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="procurement/labels/back/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="label_front_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="procurement/labels/front/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
