# Generated by Django 5.2.11 on 2026-03-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "procurement",
            "0002_purchase_receipt_image_purchaseitem_label_back_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="price_tag_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="procurement/prices/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="procurement/products/%Y/%m/%d"
            ),
        ),
    ]
