# Generated by Django 5.2.11 on 2026-02-25 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUIRES_ACTION", "REQUIRES_ACTION"),
                            ("PROCESSING", "PROCESSING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                            ("CANCELED", "CANCELED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="REQUIRES_ACTION",
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "provider_intent_ref",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("client_payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intents",
                        to="orders.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "idempotency_key"),
                        name="orders_paymentintent_payment_idempotency_unique",
                    )
                ],
            },
        ),
    ]
