# Generated by Django 5.2.11 on 2026-02-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_paymentwebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                    ("DELIVERED", "DELIVERED"),
                    ("RECEIVED", "RECEIVED"),
                    ("CANCELED", "CANCELED"),
                ],
                default="CREATED",
                max_length=16,
            ),
        ),
    ]
