# Generated by Django 5.2.11 on 2026-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LABEL_FRONT", "LABEL_FRONT"),
                            ("LABEL_BACK", "LABEL_BACK"),
                            ("RECEIPT", "RECEIPT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSED", "PROCESSED"),
                            ("APPLIED", "APPLIED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("image", models.ImageField(upload_to="ocr/jobs/%Y/%m/%d")),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
