# Generated by Django 5.2.11 on 2026-03-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LABEL_FRONT", "LABEL_FRONT"),
                    ("LABEL_BACK", "LABEL_BACK"),
                    ("PRODUCT", "PRODUCT"),
                    ("PRICE_TAG", "PRICE_TAG"),
                    ("RECEIPT", "RECEIPT"),
                ],
                max_length=16,
            ),
        ),
    ]
