# Generated by Django 5.2.11 on 2026-02-26 17:16

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Conta corrente"),
                            ("CASH", "Dinheiro"),
                            ("CARD", "Cartao"),
                            ("SAVINGS", "Poupanca"),
                        ],
                        default="CHECKING",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saida")],
                        default="OUT",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month_ref", models.DateField()),
                (
                    "limit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="personal_finance.personalcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-month_ref", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saida")], max_length=8
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("entry_date", models.DateField(default=datetime.date.today)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="personal_finance.personalaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="personal_finance.personalcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="personalaccount",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="personal_account_owner_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalcategory",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "direction"),
                name="personal_category_owner_name_direction_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalbudget",
            constraint=models.UniqueConstraint(
                fields=("owner", "category", "month_ref"),
                name="personal_budget_owner_category_month_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="personalentry",
            index=models.Index(
                fields=["owner", "entry_date"], name="personal_entry_owner_date_idx"
            ),
        ),
    ]
