# Generated by Django 5.2.11 on 2026-02-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LIST", "Consulta"),
                            ("RETRIEVE", "Detalhe"),
                            ("CREATE", "Criacao"),
                            ("UPDATE", "Atualizacao"),
                            ("DELETE", "Exclusao"),
                            ("EXPORT", "Exportacao"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resource_type", models.CharField(max_length=40)),
                ("resource_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "created_at"],
                        name="personal_audit_owner_date_idx",
                    )
                ],
            },
        ),
    ]
