# Generated by Django 5.2.11 on 2026-02-26 19:27

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_finance", "0002_personalauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personalentry",
            name="import_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="personalentry",
            name="recurring_event_key",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name="PersonalImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Preview concluido"),
                            ("CONFIRMED", "Importacao confirmada"),
                            ("FAILED", "Falha no processamento"),
                        ],
                        default="PREVIEWED",
                        max_length=16,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("delimiter", models.CharField(default=",", max_length=1)),
                ("preview_rows", models.JSONField(blank=True, default=list)),
                ("error_rows", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("rows_valid", models.PositiveIntegerField(default=0)),
                ("rows_invalid", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="personalentry",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_entries",
                to="personal_finance.personalimportjob",
            ),
        ),
        migrations.CreateModel(
            name="PersonalRecurringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrada"), ("OUT", "Saida")], max_length=8
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("WEEKLY", "Semanal"), ("MONTHLY", "Mensal")],
                        default="MONTHLY",
                        max_length=16,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_run_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rules",
                        to="personal_finance.personalaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rules",
                        to="personal_finance.personalcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_finance_recurring_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_date", "id"],
            },
        ),
        migrations.AddField(
            model_name="personalentry",
            name="recurring_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materialized_entries",
                to="personal_finance.personalrecurringrule",
            ),
        ),
        migrations.AddIndex(
            model_name="personalentry",
            index=models.Index(
                fields=["owner", "import_hash"], name="pf_entry_owner_import_hash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalentry",
            constraint=models.UniqueConstraint(
                fields=("owner", "recurring_event_key"),
                name="personal_entry_owner_recur_event_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalentry",
            constraint=models.UniqueConstraint(
                fields=("owner", "import_hash"),
                name="personal_entry_owner_import_hash_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="personalimportjob",
            index=models.Index(
                fields=["owner", "status"], name="pf_import_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalrecurringrule",
            index=models.Index(
                fields=["owner", "next_run_date"], name="pf_rule_owner_next_run_idx"
            ),
        ),
    ]
