# Generated by Django 5.2.11 on 2026-02-27 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=180)),
                ("preferred_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("secondary_phone", models.CharField(blank=True, max_length=32)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("cnpj", models.CharField(blank=True, max_length=18)),
                ("rg", models.CharField(blank=True, max_length=32)),
                ("occupation", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=16)),
                ("street", models.CharField(blank=True, max_length=160)),
                ("street_number", models.CharField(blank=True, max_length=32)),
                ("address_complement", models.CharField(blank=True, max_length=120)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=80)),
                (
                    "country",
                    models.CharField(blank=True, default="Brasil", max_length=80),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("RG", "RG"),
                            ("CNH", "CNH"),
                            ("PASSAPORTE", "Passaporte"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=16,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=64)),
                ("document_issuer", models.CharField(blank=True, max_length=120)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts/profile/%Y/%m/%d"
                    ),
                ),
                (
                    "document_front_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/documents/front/%Y/%m/%d",
                    ),
                ),
                (
                    "document_back_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/documents/back/%Y/%m/%d",
                    ),
                ),
                (
                    "document_selfie_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/documents/selfie/%Y/%m/%d",
                    ),
                ),
                (
                    "biometric_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="accounts/biometric/%Y/%m/%d"
                    ),
                ),
                (
                    "biometric_status",
                    models.CharField(
                        choices=[
                            ("NOT_CONFIGURED", "Nao configurada"),
                            ("PENDING_REVIEW", "Aguardando validacao"),
                            ("VERIFIED", "Validada"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="NOT_CONFIGURED",
                        max_length=24,
                    ),
                ),
                ("biometric_captured_at", models.DateTimeField(blank=True, null=True)),
                ("biometric_verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
    ]
