# Generated by Django 5.2.11 on 2026-02-27 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_userprofile_email_verification_last_client_base_url_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGovernanceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativa"),
                            ("UNDER_REVIEW", "Em revisao"),
                            ("SUSPENDED", "Suspensa"),
                            ("BLOCKED", "Bloqueada"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("account_status_reason", models.TextField(blank=True)),
                ("checkout_blocked", models.BooleanField(default=False)),
                ("checkout_block_reason", models.CharField(blank=True, max_length=255)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "privacy_policy_accepted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("marketing_opt_in_at", models.DateTimeField(blank=True, null=True)),
                ("marketing_opt_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lgpd_data_export_last_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "lgpd_data_anonymized_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "kyc_review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovada"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("kyc_review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_governance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_governance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLgpdRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("protocol_code", models.CharField(max_length=40, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Acesso aos dados"),
                            ("CORRECTION", "Correcao de dados"),
                            ("DELETION", "Eliminacao de dados"),
                            ("ANONYMIZATION", "Anonimizacao"),
                            ("PORTABILITY", "Portabilidade"),
                            ("REVOCATION", "Revogacao de consentimento"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluida"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("APP", "App"),
                            ("WEB", "Web"),
                            ("EMAIL", "E-mail"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PHONE", "Telefone"),
                            ("IN_PERSON", "Presencial"),
                        ],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                ("requested_by_name", models.CharField(blank=True, max_length=180)),
                ("requested_by_email", models.EmailField(blank=True, max_length=254)),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lgpd_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lgpd_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
            },
        ),
    ]
