# Generated by Codex on 2026-02-27

from django.conf import settings
from django.db import migrations


def backfill_cliente_role_for_legacy_users(apps, schema_editor):
    role_model = apps.get_model("accounts", "Role")
    user_role_model = apps.get_model("accounts", "UserRole")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(user_app_label, user_model_name)

    cliente_role, _created = role_model.objects.get_or_create(
        code="CLIENTE",
        defaults={
            "name": "Cliente",
            "description": "Usuario final para pedidos.",
            "is_active": True,
        },
    )
    if not cliente_role.is_active:
        cliente_role.is_active = True
        cliente_role.save(update_fields=["is_active", "updated_at"])

    legacy_users = (
        user_model.objects.filter(is_staff=False, is_superuser=False)
        .filter(user_roles__isnull=True)
        .only("id")
    )

    user_roles_to_create = [
        user_role_model(user_id=user.id, role_id=cliente_role.id)
        for user in legacy_users
    ]
    if user_roles_to_create:
        user_role_model.objects.bulk_create(
            user_roles_to_create,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_customergovernanceprofile_customerlgpdrequest",
        )
    ]

    operations = [
        migrations.RunPython(
            backfill_cliente_role_for_legacy_users,
            migrations.RunPython.noop,
        )
    ]
