# Generated by Django 5.2.11 on 2026-03-01 22:53

import apps.accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_phone_is_whatsapp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "ADD COLUMN IF NOT EXISTS email_login_allowed_dev "
                        "boolean DEFAULT true"
                    ),
                    reverse_sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "DROP COLUMN IF EXISTS email_login_allowed_dev"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="customergovernanceprofile",
                    name="email_login_allowed_dev",
                    field=models.BooleanField(default=True),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "ADD COLUMN IF NOT EXISTS notifications_opt_in_at "
                        "timestamp with time zone"
                    ),
                    reverse_sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "DROP COLUMN IF EXISTS notifications_opt_in_at"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="customergovernanceprofile",
                    name="notifications_opt_in_at",
                    field=models.DateTimeField(blank=True, null=True),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "ADD COLUMN IF NOT EXISTS notifications_opt_out_at "
                        "timestamp with time zone"
                    ),
                    reverse_sql=(
                        "ALTER TABLE accounts_customergovernanceprofile "
                        "DROP COLUMN IF EXISTS notifications_opt_out_at"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="customergovernanceprofile",
                    name="notifications_opt_out_at",
                    field=models.DateTimeField(blank=True, null=True),
                )
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cnpj_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cpf_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="document_number_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rg_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address_complement",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cnpj",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cpf",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="document_issuer",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="document_number",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="neighborhood",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="postal_code",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="rg",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="secondary_phone",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="street",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="street_number",
            field=apps.accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.CreateModel(
            name="CustomerSupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberto"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("WAITING_CUSTOMER", "Aguardando cliente"),
                            ("RESOLVED", "Resolvido"),
                            ("CLOSED", "Encerrado"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baixa"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "Alta"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("APP", "App"),
                            ("EMAIL", "E-mail"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PHONE", "Telefone"),
                        ],
                        default="WEB",
                        max_length=12,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Cliente"),
                            ("AGENT", "Agente"),
                            ("SYSTEM", "Sistema"),
                        ],
                        default="CUSTOMER",
                        max_length=12,
                    ),
                ),
                ("message", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.customersupportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
